### ISSUE TITLE
Inconsistent Engels/Nederlands

### ISSUE THREAD

**Issue by Maik-C** [HarryFrissr/VolenteerMatching#10]
Front-end gedeelte, gebruikt zowel Engels als Nederlands, wellicht een van de twee kiezen? :+1:

**Comment by HarryFrissr** [comment]
Engels als default

**Comment by HarryFrissr** [comment]
Er wordt gekeken voor een oplossing.

**Comment by Hiltje** [comment]
Ik ga naar translations kijken
