### ISSUE TITLE
Een probleem?

### ISSUE THREAD

**Issue by mpisters** [HarryFrissr/VolenteerMatching#26]
Ik wilde de symfony/routing package installeren maar ik kreeg steeds de melding:

 [Seld\JsonLint\ParsingException]  
  "./composer.lock" does not contain valid JSON  
  Parse error on line 8:  
  ...39086941272af",    <<<<<<< HEAD  
  ---------------------^  
  Expected: 'STRING' - It appears you have an extra trailing comma 

Nu heb ik : 
<<<<<<< HEAD
    "hash": "9ce5b95ee7a2cb1a93d53d9bc3122aae",
#     "content-hash": "3ff30f4625d58ac98448b02a65b2de35",

```
"hash": "908755995225efec51765e01c7a51a43",
"content-hash": "678bc17e17c61d44ccfeae48df061255",
```

> > > > > > > c0ee849dd6a1133f7aa498f8a7910bad9f9b69bf

dit verwijdert uit het composer.lock file en kan ik wel symfony/routing installeren.

Maar nu weet ik niet of dit een probleem zal opleveren later?

**Comment by HarryFrissr** [comment]
@mpisters De oorzaak was dat er een bestand 'foutief' is gemerged en is gecommit. Dit 'mag' niet voorkomen. 

Je oplossing :+1: was correct, btw.

Heb je nog iets concreets kunnen doen met routing?
