### ISSUE TITLE
Kan migrateDatabaseController niet uitvoeren

### ISSUE THREAD

**Issue by marloutoyou** [HarryFrissr/VolenteerMatching#39]
Fatal error: Class 'Frissr\Volunteer\Controller\Frissr\Volunteer\Controller\Controller' not found in C:\Users\marlou\Documents\bootcampPHP\VolunteerMatching\src\Frissr\Volunteer\Controller\migrateDatabaseController.php on line 14

**Comment by HarryFrissr** [comment]
@marloutoyou Oorzaak was foutieve aanroep. 

Je kan de klasse niet direct aanroepen. Je dient de Controller te benaderen via de webbrowser.
