### ISSUE TITLE
Foutmelding wanneer app.php probeer te openen. Kan index.debug.html niet vinden

### ISSUE THREAD

**Issue by Hiltje** [HarryFrissr/VolenteerMatching#40]
Ik kreeg een foutmelding wanneer ik app.php probeerde te openen. De fout dit hem erin dat op lijn 16 en 26 
https://github.com/HarryFrissr/VolenteerMatching/blob/master/src/frissr/volunteer/Controller/indexController.php#L16

https://github.com/HarryFrissr/VolenteerMatching/blob/master/src/frissr/volunteer/Controller/indexController.php#L26

index.... staat geschreven en moet worden index/.....

**Comment by marloutoyou** [comment]
Ik heb dit ook met andere bestanden. Volgens mij zit er ergens in dit MVC netwerk een fout (sowieso staat er soms bij de namespace volenteer ipv volunteer) en t is nu moeilijk om te vinden waar omdat alles in andere mapjes zit. En php dus niet kan zeggen op welke regel iets fout gaat.

**Comment by HarryFrissr** [comment]
:+1: @marloutoyou Ik zag dat je deze fouten heb opgelost. Top,
